### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by neesonqk** [necipakif/minikSuElcileri#1]
May I know what is the font?

![145392353-fbd06c7d-f867-4e58-bd86-edacafa5f216](https://user-images.githubusercontent.com/7279067/219269454-68930543-8a6e-4910-94cf-def7719c4929.png)

**Comment by necipakif** [comment]
Sorry, but I don't remember at all.  Let me point out two fonts that I love and use right now.  One is Victor Mono, the other is Fira Code Retina.

fontSize:14
fontWeight:600,
lineHeight:26

theme: Tokyo Night Storm
